### ISSUE TITLE
Crash on placing a prefab with `ChangingBlock` property

### ISSUE THREAD

**Issue by jdrueckert** [Terasology/ChangingBlocks#14]
### How to reproduce

1. Start Terasology
2. Select `CoreGameplay` and add the `PlantPack` and `ChangingBlocks` modules in the Advanced Game Setup (AGS)
3. Open the in-game console (F1) and execute `give corn1`
4. Select the new item in your inventory quickslot bar and right-click to place it on a dirt/grass block
5. Observe Terasology crashing

**Comment by keturn** [comment]
It looks like [SimpleUri](https://github.com/MovingBlocks/Terasology/blob/v5.2.0/engine/src/main/java/org/terasology/engine/core/SimpleUri.java) is what we use for normalized prefab URIs.

**Comment by jdrueckert** [comment]
Thanks for that pointer :+1: 
It seems our prefab deserialization does not support deserializing into `SimpleUri`s yet :disappointed: 
Guess I'll go for some workaround + engine issue and associated in-code `TODO`...

**Comment by jdrueckert** [comment]
While #15 fixes the `ChangingBlocks` side of this bug, following the reproduction steps will still lead to a crash.
If tested with https://github.com/MovingBlocks/Terasology/pull/5062, it will no longer crash but still not work yet (and log warnings).
If tested with https://github.com/Terasology/PlantPack/pull/20, it should work.
